import { PostItem } from "@/src/types";

export const PostData: PostItem[] = [
    {
        id: '1',
        name: 'testing',
        location: 'Noida, Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Technology | ',
        views: '3 Views',
        discription: 'Exploring next generation computing architecture and intelligent systems.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Technology',
    },
    {
        id: '2',
        name: 'zoya',
        location: 'Jaipur, Rajasthan',
        imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Nature | ',
        views: '30 Views',
        discription: 'Serene morning views from the hills. Nature never fails to amaze.',
        fullLocation: 'Mansarovar, Jaipur, Rajasthan, 302020',
        category: 'Lifestyles',
    },
    {
        id: '3',
        name: 'Anonymouse',
        location: 'Noida, Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Architecture | ',
        views: '30k Views',
        discription: 'Modern glass skyscraper design reflecting future business hubs.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Business',
    },
    {
        id: '4',
        name: 'tupen',
        location: 'Bishnupur, West Bengal',
        imageUrl: 'https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Business | ',
        views: '3 Views',
        discription: 'Global market insights and daily financial briefing overview.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Business',
    },
    {
        id: '5',
        name: 'tupen',
        location: 'Bishnupur, West Bengal',
        imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Entertainment | ',
        views: '3 Views',
        discription: 'Live concert moments and stage lights from the weekend festival.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Entertainment',
    },
    {
        id: '6',
        name: 'Ritu',
        location: 'West Bengal',
        imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'EndLessPoint | ',
        views: '31 Views',
        discription: 'Just for fun and celebrations with friends.',
        fullLocation: 'Meerut Division, UK 20209',
        category: 'Entertainment',
    },
    {
        id: '7',
        name: 'Rohan Jha',
        location: 'Goa',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Lifestyles | ',
        views: '300k Views',
        discription: 'Sunset by the beach in North Goa, refreshing vibes.',
        fullLocation: 'Goa, Meerut Division, UH 30394',
        category: 'Lifestyles',
    },
    {
        id: '8',
        name: 'Aman Verma',
        location: 'Baliya UP 20303',
        imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Sports | ',
        views: '20k Views',
        discription: 'Stadium atmosphere under the floodlights during the championship game.',
        fullLocation: 'Baliya UP 20303, Jaunpur',
        category: 'Sports',
    },
    {
        id: '9',
        name: 'VijayMal Yadav',
        location: 'Jaunpur Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Sports | ',
        views: '10k Views',
        discription: 'High energy sports action on the court.',
        fullLocation: 'Jaunpur, Uttar Pradesh 20003',
        category: 'Sports',
    },
    {
        id: '10',
        name: 'Shivam Singh',
        location: 'Ayodhya Uttar Pradesh 1229',
        imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Sports | ',
        views: '5k Views',
        discription: 'Training session focus and game day prep.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Sports',
    },
    {
        id: '11',
        name: 'Nihar',
        location: 'Noida, Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Technology | ',
        views: '3 Views',
        discription: 'Cybersecurity and modern backend engineering architecture.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Technology',
    },
    {
        id: '12',
        name: 'Prv Verma',
        location: 'Noida, Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Technology | ',
        views: '1k Views',
        discription: 'Tech Hub showcase: hardware developments and modern interfaces.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Technology',
    },
    {
        id: '13',
        name: 'testing',
        location: 'Noida, Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Health | ',
        views: '3 Views',
        discription: 'Morning wellness habits and balanced daily nutrition advice.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Health',
    },
    {
        id: '14',
        name: 'testing',
        location: 'Noida, Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Health | ',
        views: '3 Views',
        discription: 'Medical research and preventive healthcare updates.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Health',
    },
    {
        id: '15',
        name: 'testing',
        location: 'Noida, Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Health | ',
        views: '3 Views',
        discription: 'Mindfulness, meditation, and daily mental health practices.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Health',
    },
    {
        id: '16',
        name: 'testing',
        location: 'Noida, Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Health | ',
        views: '3 Views',
        discription: 'Clinical advancements and public health insights.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Health',
    },
    {
        id: '17',
        name: 'Anonymouse',
        location: 'Noida, Uttar Pradesh',
        imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
        postDate: 'Jul 1, 2025',
        postContent: 'Government | ',
        views: '30k Views',
        discription: 'Urban development policies and public infrastructure expansion.',
        fullLocation: 'Noida Sector 3, Noida, Meerut Division, UP',
        category: 'Government',
    },
];
